swagger: "2.0"
info:
  title: API Documentation
  description: API Documentation
  version: 1.0.0

host: localhost:3000
basePath: /
schemes:
  - http

paths:
  /yml:
    get:
      summary: Returns yml converted content.
      produces:
        - application/json
      responses:
        200:
          description: OK
  /xml:
    get:
      summary: Returns xml converted content.
      produces:
        - application/json
      responses:
        200:
          description: OK
